Changes related to in-neovim lazygit and c++ running and debugging

diff --git a/scripts/cr b/scripts/cr
--- a/scripts/cr
+++ b/scripts/cr
@@ -9,28 +9,62 @@ fi
 
 filename="$1"
 
-filename="${filename%.*}"
+filename="${filename%.*}.o"
 
-flag="-std=c++23 -O2 -Wall -Wextra -Wshadow -Wconversion -Wfloat-equal"
+# flag="-std=c++23 -O2"
+flag="-std=c++23 -Wall -Wextra -Wshadow -Wconversion -lmatplot"  
 # flag="-std=c++20 -O2 -Wall -Wextra -Wshadow -Wconversion -Wfloat-equal -Wl,-ld_classic,-stack_size,0x10000000"
 
 dbgFlag="-fsanitize=address -fsanitize=undefined -fsanitize=float-divide-by-zero -fsanitize=float-cast-overflow -fno-sanitize-recover=all -fstack-protector-all -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -g"
 
 if [ "$2" == "-d" ]; then
-  printf "Using lldb (use r (run) and bt (backtrace))"
+  # printf "Using lldb (use r (run) and bt (backtrace))"
+  #
+  # # printf "g++ $1 -o $filename $flag $dbgFlag && lldb $filename"
+  # printf "g++ $1 -o $filename $flag $dbgFlag"
+  #
+  # # printf "\n\nCompiled with DEBUG flags enabled, code may be slower than normal"
+  # printf "\n\n|---- \e[0;34mDebugging\e[m ----|\n\n"
+  #
+  # g++ $1 -o $filename $flag $dbgFlag
+  #
+  # g++ $1 -o $filename $flag && lldb $filename
+  #
+  printf "g++ $1 -o $filename $flag $dbgFlag -O0"
 
-  printf "gcc $1 -o $filename $flag && lldb $filename"
+  printf "\n\n|----\e[0;34m Compilation output (debug) \e[m----|\n\n"
 
-  # printf "\n\nCompiled with DEBUG flags enabled, code may be slower than normal"
-  printf "\n\n|---- \e[0;34mDebugging\e[m ----|\n\n"
+  g++ $1 -o $filename $flag $dbgFlag
 
-  gcc $1 -o $filename $flag && lldb $filename
+  if [ $? -ne 0 ]; then
+    printf "\n\n|----\e[0;31m\033[1m Errors found \e[m----|\n\n"
+    exit 1
+  # else
+  #   printf "\n|----\e[0;34m No errors \e[m----|\n\n"
+  #   exit
+  fi
+
+
+  printf "\n|----\e[0;34m Running (Input) \e[m----|\n\n"
+
+  # if the filename is not equal to a slash then add a ./ in front
+
+  if [ "${filename:0:1}" != "/" ]; then
+    filename="./$filename"
+  fi
+
+  # replace gtime with time on linux operating systems
+  # \time -f '\n|--------|\n\n  real\t%E\n  user\t%U\n  sys\t%S\n  mem\t%MKB\n' $filename
+  output=$(\time -f '\n|----------------|\n\n  real\t%E\n  user\t%U\n  sys\t%S\n  mem\t%MKB\n' $filename 2>&1)
+  printf "\n|----\e[0;34m Running (Output) \e[m----|\n\n"
+  printf "$output\n\n"
+  #
 else
-  printf "gcc $1 -g -o $filename $flag"
+  printf "g++ $1 -o $filename $flag -O3"
 
   printf "\n\n|----\e[0;34m Compilation output \e[m----|\n\n"
 
-  gcc $1 -o $filename $flag
+  g++ $1 -o $filename $flag
 
   if [ $? -ne 0 ]; then
     printf "\n\n|----\e[0;31m\033[1m Errors found \e[m----|\n\n"
@@ -46,8 +80,8 @@ else
   fi
 
   # replace gtime with time on linux operating systems
-  gtime -f '\n|--------|\n\n  real\t%E\n  user\t%U\n  sys\t%S\n  mem\t%MKB\n' $filename
-  # output=$(gtime -f '\n|--------|\n\n  real\t%E\n  user\t%U\n  sys\t%S\n  mem\t%MKB\n' $filename 2>&1)
-  # printf "\n|----\e[0;34m Running (Output) \e[m----|\n\n"
-  # printf "$output\n\n"
+  # \time -f '\n|--------|\n\n  real\t%E\n  user\t%U\n  sys\t%S\n  mem\t%MKB\n' $filename
+  output=$(\time -f '\n|----------------|\n\n  real\t%E\n  user\t%U\n  sys\t%S\n  mem\t%MKB\n' $filename 2>&1)
+  printf "\n|----\e[0;34m Running (Output) \e[m----|\n\n"
+  printf "$output\n\n"
 fi
